### ISSUE TITLE
Block incoming items

### ISSUE THREAD

**Issue by HeyndrickxKarel** [buttonwoodcx/bcx-aurelia-dnd#15]
Hi

Could it be possible to create a scenario where you have multiple lists where you can d&d items and also a sort of master list from which u can only take items? So you can't put items in there by d&d'ing from the multiple lists towards it?

**Comment by 3cp** [comment]
It's possible if you go down to pure bcx-aurelia-dnd without reorderable-repeat. Something like https://buttonwoodcx.github.io/doc-bcx-aurelia-dnd/#/e6-reorder-list but with multiple lists, there will be lot more verbose code.

I also used mixed bcx-aurelia-dnd + reorderable-repeat in some app, but rely on some internal repeat-id of reorderable-repeat (the id is not documented as public api). I will add some example to the doc site if it's reasonable to follow for the readers. Otherwise I will try to finalise some api for reorderable-repeat to easily collaborate with other bcx-aurelia-dnd parts.

Bit busy. I will get back to you early next week.

**Comment by 3cp** [comment]
https://buttonwoodcx.github.io/doc-bcx-aurelia-dnd/#/er8-multi-lists-mix-with-aurelia-dnd

This new demo uses internal reorderable-repeat model shape for bcx-aurelia-dnd to talk with some repeats. I probably should publish this internal model shape in the official doc of reorderable-repeat.

Follow the code comments, note the code to remove if you don't want to put items back to your master list.

**Comment by 3cp** [comment]
Note I committed a bug fix to the demo's `repository.js`.

**Comment by 3cp** [comment]
@HeyndrickxKarel If that demo is sufficient for you, please close this issue. Thx.

**Comment by HeyndrickxKarel** [comment]
Oh my bad! That demo is indeed sufficient. I just didn't know I was the one who had to close the issue :).

**Comment by 3cp** [comment]
NVM. I can close it too, but waited for your confirmation.
