### ISSUE TITLE
Idea for resizing

### ISSUE THREAD

**Issue by seriouz** [buttonwoodcx/bcx-aurelia-dnd#5]
Hi @huochunpeng, do you have a solution for resizing boxes when using bcx-aurelia-dnd? Where do i have to hook up in your code? I want to resize when i grab the edges (with little a treshold) and dragging when i grab the middle of a box.

**Comment by seriouz** [comment]
Thank you very much!

**Comment by huochunpeng** [comment]
Let me know if it's sufficient.
https://buttonwoodcx.github.io/doc-bcx-aurelia-dnd/#/e7-move-and-resize

**Comment by seriouz** [comment]
Its working very very well! Thanks you again! But i have another problem:
The `<div>` what i am dragging has a css transform rotation `<div style="transform: rotate(45deg); transform-origin: 50% 50% 0px;">Hello</div>` and the box is jumping during dragging (preview) and has the wrong drop location.

**Comment by huochunpeng** [comment]
You need to be really careful with transform, it works in different coordinate. It will spin your head.

Don't use previewElementRect, targetElementRect. Only use mouseStartAt and mouseEndAt (for both move and resize), calculate a delta like I did.

Next, depending on which DOM you put transform on, you need to do an affine transform to transform the delta to intended delta change.

There is one implementation of affine transform in JS http://paperjs.org/reference/matrix

For the transform you mentioned, I think you need a reversed affine transform (rotate -45deg) on the delta for resize.

You definitely need some sort of reversed transform on delta for resize, I don't think you need any for move. The box jumping is probably due to you used previewElementRect. But I didn't test any of my above guessing, plus I don't know your exact DOM structure.

Help some fun with affine transform, it might bring back some of your lovely (or terrible 😄) memory as a student. If you still need more help, contact me on gitter. For this issue, I will close it.
